[package]
name = "semifold-engine"
version = "0.2.3"
edition.workspace = true
description.workspace = true
license.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
readme.workspace = true

[dependencies]
bytes = "1.10.1"
camino = { version = "1.2.4", features = ["serde1"] }
git2 = { version = "0.21.0", features = ["vendored-openssl"] }
glob = "0.3.4"
httpdate = "1.0.3"
minijinja = { version = "2.12.0", default-features = false, features = ["serde"] }
octocrab = "0.54.1"
reqwest = { version = "0.13.4", default-features = false, features = ["json", "rustls"] }
semifold-changelog = { version = "0.3.2", path = "../changelog" }
semifold-core = { version = "0.1.1", path = "../semifold-core" }
semifold-resolver = { version = "0.4.2", path = "../resolver" }
semver = "1.0.28"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
thiserror = "2.0.18"
tokio = { version = "1.48.0", features = ["time"] }
toml_edit = { version = "0.25.13", features = ["serde"] }

[lints]
workspace = true

[dev-dependencies]
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
