[package]
name = "semifold-changelog"
version = "0.3.2"
edition.workspace = true
description.workspace = true
license.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
git2 = { version = "0.21.0", features = ["vendored-openssl"] }
minijinja = { version = "2.12.0", default-features = false, features = ["builtins", "serde"] }
octocrab = "0.54.1"
pathdiff = "0.2.3"
semifold-core = { version = "0.1.1", path = "../semifold-core" }
semifold-resolver = { version = "0.4.1", path = "../resolver" }
semver = "1.0.28"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.17"

[dev-dependencies]
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
